development: {}
staging: {}
production:
  cleanup_expired_drafts:
    class: "CleanupExpiredDraftsJob"
    schedule: at 1am every day
  # ? we disabled this, because we need to show the past of the availabilities
  # clean_up_past_availabilities:
  #   class: "CleanUpPastAvailabilitiesJob"
  #   schedule: at 1am every day
  # ? we disabled this, because there is request about editing the past non cancelled appointment
  # cancel_past_appointments:
  #   class: "CancelPastAppointmentsJob"
  #   schedule: at 1am every day
